/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.adminScreen;

import view.customerScreen.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Employee;
import view.employeeScreen.manageFranchiseScreen;

/**
 *
 * @author akshb
 */
public class RMMainScreen extends javax.swing.JPanel {

    JPanel userProcessPanel;
    Employee sessionUser;

    public RMMainScreen(JPanel userProcessPanel, Employee sessionUser) {
        initComponents();
        this.sessionUser = sessionUser;
        this.userProcessPanel = userProcessPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        csrButton = new javax.swing.JButton();
        franchiseButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(866, 510));
        setMinimumSize(new java.awt.Dimension(866, 510));

        csrButton.setBackground(new java.awt.Color(255, 204, 204));
        csrButton.setText("Manage CSR");
        csrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csrButtonActionPerformed(evt);
            }
        });

        franchiseButton.setBackground(new java.awt.Color(255, 204, 204));
        franchiseButton.setText("Manage Franchise");
        franchiseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                franchiseButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to PACK-MAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(354, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(franchiseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(340, 340, 340))
            .addGroup(layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(95, 95, 95)
                .addComponent(csrButton)
                .addGap(55, 55, 55)
                .addComponent(franchiseButton)
                .addContainerGap(286, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void csrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csrButtonActionPerformed
        AdminMainScreen adminMainScreen = new AdminMainScreen(userProcessPanel, sessionUser);
        userProcessPanel.add("AdminMainScreen", adminMainScreen);
        CardLayout layout = (CardLayout) userProcessPanel.getLayout();
        layout.next(userProcessPanel);
    }//GEN-LAST:event_csrButtonActionPerformed

    private void franchiseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_franchiseButtonActionPerformed
        // TODO add your handling code here:
        manageFranchiseScreen manageFranchiseScreen = new manageFranchiseScreen(userProcessPanel, sessionUser);
        userProcessPanel.add("manageFranchiseScreen", manageFranchiseScreen);
        CardLayout layout = (CardLayout) userProcessPanel.getLayout();
        layout.next(userProcessPanel);
    }//GEN-LAST:event_franchiseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton csrButton;
    private javax.swing.JButton franchiseButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
