/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.employeeScreen;

import DBConnection.DBConnect;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.PackageManagementEnterprise.Package;
import view.packageEditScreen;

/**
 *
 * @author akshb
 */
public class retrievePackagesScreen extends javax.swing.JPanel {

    /**
     * Creates new form existingPackageApprovalScreen
     */
    DBConnection.DBConnect dbConnect;
    JPanel userProcessPanel;

    public retrievePackagesScreen(JPanel userProcessPanel) {
        initComponents();
        populatePackageTable();
        dbConnect = new DBConnect();
        this.userProcessPanel = userProcessPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        cancelPackageButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        packagesTable = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(866, 510));
        setMinimumSize(new java.awt.Dimension(866, 510));
        setPreferredSize(new java.awt.Dimension(860, 540));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Retrieve Packages");

        cancelPackageButton.setText("Cancel Package");
        cancelPackageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPackageButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update Package");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        packagesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tracking ID", "Sender Name", "Location", "Provider"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(packagesTable);
        if (packagesTable.getColumnModel().getColumnCount() > 0) {
            packagesTable.getColumnModel().getColumn(0).setResizable(false);
            packagesTable.getColumnModel().getColumn(1).setResizable(false);
            packagesTable.getColumnModel().getColumn(2).setResizable(false);
            packagesTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jLabel11)
                .addContainerGap(355, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelPackageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateButton)
                .addGap(18, 18, 18)
                .addComponent(cancelPackageButton)
                .addGap(248, 248, 248))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelPackageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPackageButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) packagesTable.getModel();
        int selectedRow = packagesTable.getSelectedRow();
        Package selectedPkg;
        if (selectedRow != -1) {
            selectedPkg = (Package) model.getValueAt(selectedRow, 0);
            if (selectedPkg != null) {
                selectedPkg.getStatusHistory().add(selectedPkg.getStatus());
                selectedPkg.setStatus(4);
            }
        }
    }//GEN-LAST:event_cancelPackageButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) packagesTable.getModel();
        int selectedRow = packagesTable.getSelectedRow();
        Package selectedPkg;
        if (selectedRow != -1) {
            selectedPkg = (Package) model.getValueAt(selectedRow, 0);
            if (selectedPkg != null) {
                packageEditScreen packageEditScreen = new packageEditScreen(userProcessPanel, selectedPkg);
                userProcessPanel.add("packageEditScreen", packageEditScreen);
                CardLayout layout = (CardLayout) userProcessPanel.getLayout();
                layout.next(userProcessPanel);
            }
        }
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelPackageButton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable packagesTable;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    private void populatePackageTable() {
        DefaultTableModel model = (DefaultTableModel) packagesTable.getModel();
        model.setRowCount(0);

        Package p = new Package();
        dbConnect.open();
        ArrayList<Package> result = dbConnect.getListOf(p);
        dbConnect.close();
        for (Package pkg : result) {
            Object[] row = new Object[4];
            row[0] = pkg;
            row[1] = pkg.getFromName();
            row[2] = pkg.getCurrentLocationCity();
            row[3] = common.Enum.PackageProvider.values()[pkg.getProvider()];
            model.addRow(row);
        }
    }
}
