/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.customerScreen;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Customer;

/**
 *
 * @author aishwaryanagaraj
 */
public class customerMainScreen extends javax.swing.JPanel {

    JPanel userProcessPanel;
    Customer sessionUser;

    public customerMainScreen(JPanel userProcessPanel, Customer sessionUser) {
        initComponents();
        this.userProcessPanel = userProcessPanel;
        this.sessionUser = sessionUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        trackShipmentButton = new javax.swing.JButton();
        contactUsButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(866, 510));
        setMinimumSize(new java.awt.Dimension(866, 510));
        setPreferredSize(new java.awt.Dimension(860, 540));

        jSplitPane1.setDividerSize(2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        searchButton.setBackground(new java.awt.Color(255, 204, 204));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        trackShipmentButton.setBackground(new java.awt.Color(255, 204, 204));
        trackShipmentButton.setText("Track shipment");
        trackShipmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackShipmentButtonActionPerformed(evt);
            }
        });

        contactUsButton.setBackground(new java.awt.Color(255, 204, 204));
        contactUsButton.setText("Contact Us");
        contactUsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactUsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contactUsButton)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trackShipmentButton)
                    .addComponent(searchButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {contactUsButton, searchButton, trackShipmentButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(searchButton)
                .addGap(18, 18, 18)
                .addComponent(trackShipmentButton)
                .addGap(18, 18, 18)
                .addComponent(contactUsButton)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void contactUsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactUsButtonActionPerformed
        customerQueryScreen customerQuerySc = new customerQueryScreen(userProcessPanel, jSplitPane1);
        jSplitPane1.setRightComponent(customerQuerySc);

//        userProcessPanel.add("customerQueryScreen", customerQuerySc);
//        CardLayout layout = (CardLayout) userProcessPanel.getLayout();
//        layout.next(userProcessPanel);
    }//GEN-LAST:event_contactUsButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        customerSearchScreen custSearchScreen = new customerSearchScreen(userProcessPanel,sessionUser);
        jSplitPane1.setRightComponent(custSearchScreen);
//        userProcessPanel.add("customerSearchScreen", custSearchScreen);
//        CardLayout layout = (CardLayout) userProcessPanel.getLayout();
//        layout.next(userProcessPanel);

        //customerSearchScreen custSearchScreen = new customerSearchScreen(userProcessPanel);
        //jSplitPane1.setRightComponent(custSearchScreen);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void trackShipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackShipmentButtonActionPerformed
        trackShipmentScreen trackShipScreen = new trackShipmentScreen(userProcessPanel);
        jSplitPane1.setRightComponent(trackShipScreen);

//        userProcessPanel.add("trackShipmentScreen", trackShipScreen);
//        CardLayout layout = (CardLayout) userProcessPanel.getLayout();
//        layout.next(userProcessPanel);
    }//GEN-LAST:event_trackShipmentButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton contactUsButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton trackShipmentButton;
    // End of variables declaration//GEN-END:variables
}
